name: Build

on:
    workflow_call:

jobs:
    build:
        name: Run Build
        runs-on: ubuntu-latest

        steps:
            - name: Check out github repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1
                  
            - name: Setup environment and install dependencies
              uses: ./.github/actions/setup

            - name: Run Build
              run: pnpm build
