name: Main Workflow

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - dev
            - main

concurrency:
    group: ${{github.workflow}}-${{github.ref}}
    cancel-in-progress: true

jobs:
    build:
        uses: ./.github/workflows/build.yml

    lint:
        uses: ./.github/workflows/lint.yml
        needs: build

    test:
        uses: ./.github/workflows/test.yml
        needs: lint

    test-e2e:
        uses: ./.github/workflows/test-e2e.yml
        needs: lint
