name: Tests

on:
    workflow_call:

jobs:
    unit:
        name: Unit tests
        runs-on: ubuntu-latest
        steps:
            - name: Check out github repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 1

            - name: Setup environment and install dependencies
              uses: ./.github/actions/setup

            - name: Run tests with coverage
              run: pnpm test:cov
